version: "3"

vars:
    GO_MODULES:
        sh: cat go.work | grep -oEh  '\t+(\./*[^[:space:]]*)' | tr -d '\t'
    GO_ROOT_PKG:
        sh: cat go.mod | grep -oE '^module[^\S]+' | cut -d' ' -f2
    GO_COMMAND: go
    SUPPORTED_ARCHS:
      - arm64
    FORKS:
      - ../console
      - ../go-runc
      - ../ttrpc
      - ../gvisor-tap-vsock
      - ../go-errors
      - ../nerdctl
      - ../containerd
    BUILD_OUT_DIR: gen/build

env:
    COMPOSE_BAKE: true
    GOPROXY: 'https://proxy.golang.org'
    GOSUMDB: sum.golang.org
    GOPRIVATE: github.com/walteh
    DOCKER_BUILDKIT: 1

tasks:
    go:tidy:
        run: once
        aliases: [go-mod-tidy]
        cmds:
          - for: {var: GO_MODULES}
            cmd: cd {{.ITEM}} && go mod tidy -e

    go:upgrade:
        aliases: [go-mod-upgrade]
        run: once
        cmds:
          - |-
            {{.GO_COMMAND}} tool go-mod-upgrade --force
          - task: go-mod-tidy

    go:update:
        aliases: [go-mod-update]
        requires: {vars: [CLI_ARGS]}
        run: once
        cmds:
          - task: go:tidy
          - for: {var: GO_MODULES}
            cmd: cd {{.ITEM}} && go get -u {{.CLI_ARGS}}
          - task: go:tidy

    go:lint:
        desc: runs the linters
        vars:
            # GO_FILES: "./cmd/containerd-shim-runm-v2/manager/manager.go"

            # skip .gen and .pb.go files
            GO_FILES:
                sh: find . -type f -name '*.go' -not -path '*/gen/*' -not -path '*/proto/*'
        cmds:
          - for: {var: GO_FILES}
            cmd: |-
                tmp=$(mktemp); cat {{.ITEM}} | go tool goshim retab > $tmp; mv $tmp {{.ITEM}}
          - cmd: go tool golangci-lint run --fix ./...

    go:test:
        desc: runs the tests
        cmds:
          - cmd: go tool gotestsum go test ./...

    term:
        desc: opens a terminal in the project root
        platforms: [darwin]
        cmds:
          - cmd: open -a Terminal $(pwd)

    zellij:
        desc: opens zellij
        platforms: [darwin]
        cmds:
          - cmd: zellij --config-dir .zellij

    gen:all:
        desc: generates all
        cmds:
          - task: gen:options
          - task: gen:buf
          - task: gen:mockery

    gen:options:
        desc: generates options for structs with '//go:opts' comment
        vars:
            OPTION_GEN_DATA:
                sh: |-
                    grep -rl "//go:opts" --include="*.go" . | xargs -I{} bash -c 'd=$(dirname {}); d=${d#./}; awk -v d="$d {}" '\''/\/\/go:opts/ {getline; if($1=="type") print d, $2}'\'' {}' || true
            OPTION_GEN_SOURCE_FILES:
                sh: |-
                    grep -rl "//go:opts" --include="*.go" . || true
        generates:
          - "**/*_opts.gen.go"
        sources:
          - '{{.OPTION_GEN_SOURCE_FILES | join ","}}'
        cmds:
          - for: {var: OPTION_GEN_DATA, split: "\n"}
            cmd: |-
                set -e
                if [ -z "{{.OPTION_GEN_DATA}}" ]; then echo "no options to generate"; exit 0; fi
                {{.GO_COMMAND}} tool github.com/kazhuravlev/options-gen/cmd/options-gen \
                  -out-filename={{splitList " " .ITEM | first}}/{{ splitList " " .ITEM | last | lower | trimSuffix "opts" }}_opts.gen.go \
                  -filename={{ splitList " " .ITEM | rest | first }} \
                  -from-struct={{ splitList " " .ITEM | last }} \
                  -pkg={{ splitList " " .ITEM | first | splitList "/" | last }}
          - for: {var: OPTION_GEN_DATA, split: "\n"}
            cmd: |-
                go tool golangci-lint run --enable-only goimports --fix {{ splitList " " .ITEM | first }}/{{ splitList " " .ITEM | last | lower | trimSuffix "opts" }}_opts.gen.go
                gofmt -w {{ splitList " " .ITEM | first }}/{{ splitList " " .ITEM | last | lower | trimSuffix "opts" }}_opts.gen.go

    gen:mockery:
        desc: generates mocks for interfaces with '//go:mock' comment
        vars:
            TMP_DIR:
                sh: mktemp -d
            MOCKERY_INTERFACE_DATA:
                sh: |-
                    grep -rl "//go:mock" --include="*.go" . | xargs -I{} sh -c '
                        f="{}"
                        d=$(dirname "$f"); d=${d#./}
                        raw=$(awk "/\/\/go:mock/{getline; if(\$1==\"type\") print \$2}" "$f")
                        name=${raw%%\[*}
                        for i in $name; do echo "$d $f $i"; done' || true
            MOCKERY_SOURCE_FILES:
                sh: |-
                    grep -rl "//go:mock" --include="*.go" . || true
            ALL_MOCKERY_INTERFACE_DATA:
                sh: |-
                    echo "{{.MOCKERY_INTERFACE_DATA}}"
        sources:
          - '{{.MOCKERY_SOURCE_FILES | join ","}}'
          - .mockery.yaml
          - proto/**/*.pb.go
        generates:
          - ./gen/mocks/**/*_mock.gen.go
        cmds:
          - cmd: mkdir -p {{.TMP_DIR}}
          - defer: rm -rf {{.TMP_DIR}}
          - cmd: cp .mockery.yaml {{.TMP_DIR}}/.mockery.yaml

          - for: {var: "ALL_MOCKERY_INTERFACE_DATA", split: "\n", as: ITEM}
            cmd: |-
                set -e
                if [ -z "{{.ITEM}}" ]; then echo "no mockery to generate"; exit 0; fi
                yq -i ".packages.\"{{ .GO_ROOT_PKG }}/{{ splitList " " .ITEM | first }}\".interfaces.{{ splitList " " .ITEM | last }} = {}" {{.TMP_DIR}}/.mockery.yaml
          - cmd: cat {{.TMP_DIR}}/.mockery.yaml
          - cmd: |-
                {{.GO_COMMAND}} tool github.com/vektra/mockery/v3 --config={{.TMP_DIR}}/.mockery.yaml

    gen:buf:
        desc: generates protobuf files
        dir: proto
        sources:
          - '**/*.proto'
          - 'buf.*'
          - '../tools/cmd/**/*.go'
        generates:
          - '**/*.pb.go'
        cmds:
          - |-
            {{.GO_COMMAND}} tool github.com/bufbuild/buf/cmd/buf generate

    install:bindfs:
        env:
            fuse_CFLAGS: "-I/usr/local/include/fuse -D_FILE_OFFSET_BITS=64 -D_DARWIN_C_SOURCE"
            fuse_LIBS: "-L/usr/local/lib -lfuse-t -pthread"
        cmds:
          - git clone https://github.com/mpartel/bindfs.git /tmp/bindfs
          - defer: rm -rf /tmp/bindfs
          - cd /tmp/bindfs && ./autogen.sh
          - cd /tmp/bindfs && ./configure --with-fuse2
          - cd /tmp/bindfs && make
          - cd /tmp/bindfs && sudo make install
          - sudo install_name_tool -add_rpath /usr/local/lib /usr/local/bin/bindfs

    linux:kernel:*:
        label: 'linux:kernel:{{.ARCH}}'
        requires: {vars: [ARCH]}
        desc: builds the kernel
        sources:
          - ./linux/kernel/**
        generates:
          - "./{{.BUILD_OUT_DIR}}/linux_kernel_{{ .ARCH }}/**"
        vars:
            ARCH: "{{index .MATCH 0}}"
            PACKAGE: linux_kernel_{{ .ARCH }}
            OUT_DIR: "{{.BUILD_OUT_DIR}}/{{.PACKAGE}}"
            TMP_DIR:
                sh: mktemp -d
        cmds:
          - defer: rm -rf {{.TMP_DIR}}
          - cmd: mkdir -p {{.TMP_DIR}}
          - |-
            docker buildx build \
                --platform=linux/{{.ARCH}} \
                --target export \
                --output type=local,dest={{.TMP_DIR}} \
                linux/kernel
          - cmd: xz -k {{.TMP_DIR}}/kernel
          - cmd: sha256sum {{.TMP_DIR}}/kernel.xz > {{.TMP_DIR}}/kernel.xz.sha256
          - cmd: sha256sum {{.TMP_DIR}}/config > {{.TMP_DIR}}/config.sha256
          - cmd: rm {{.TMP_DIR}}/kernel
          - cmd: |-
                echo -e "package {{.PACKAGE}}\n\nimport _ \"embed\"\nimport \"github.com/walteh/runm/pkg/binembed\"\n" > {{.TMP_DIR}}/embed.gen.go
                echo -e "//go:embed kernel.xz\nvar BinaryXZ []byte\n" >> {{.TMP_DIR}}/embed.gen.go
                echo -e "const BinaryXZChecksum = \"$(cat {{.TMP_DIR}}/kernel.xz.sha256 | awk '{print $1}')\"\n" >> {{.TMP_DIR}}/embed.gen.go
                echo -e "//go:embed config\n\nvar Config []byte\n" >> {{.TMP_DIR}}/embed.gen.go
                echo -e "const ConfigChecksum = \"$(cat {{.TMP_DIR}}/config.sha256 | awk '{print $1}')\"\n" >> {{.TMP_DIR}}/embed.gen.go
                echo -e "func init() {\n\tbinembed.RegisterXZ(BinaryXZChecksum, BinaryXZ)\n\tbinembed.RegisterRaw(ConfigChecksum, Config)\n}\n" >> {{.TMP_DIR}}/embed.gen.go
          - cmd: go fmt {{.TMP_DIR}}/embed.gen.go
          - cmd: mkdir -p {{.OUT_DIR}}
          - cmd: mv -f {{.TMP_DIR}}/* {{.OUT_DIR}}

    linux:kernel:
        desc: builds the kernel
        cmds:
          - for: {var: SUPPORTED_ARCHS}
            task: linux:kernel:{{.ITEM}}

    linux:initramfs:*:
        label: 'linux:initramfs:{{.ARCH}}'
        requires: {vars: [ARCH]}
        desc: builds the initramfs
        sources:
          - ./linux/initramfs/**
        generates:
          - ./gen/build/initramfs_{{ .ARCH }}/**
        vars:
            ARCH: "{{index .MATCH 0}}"
            PACKAGE: linux_initramfs_{{ .ARCH }}
            OUT_DIR: ./gen/build/{{.PACKAGE}}
            TMP_DIR:
                sh: mktemp -d
        cmds:
          - defer: rm -rf {{.TMP_DIR}}
          - cmd: mkdir -p {{.TMP_DIR}}
          - cmd: mkdir -p {{.TMP_DIR}}/forks
          - for: {var: FORKS}
            cmd: rsync -a --exclude='vendor/' --exclude='tmp/' --exclude='.git/' {{.ITEM}} {{.TMP_DIR}}/forks/
          - |-
            docker buildx build \
                --platform=linux/{{.ARCH}} \
                --target export \
                --output type=local,dest={{.TMP_DIR}} \
                --build-context=runm=. \
                --build-context=go-path=$(go env GOPATH) \
                --build-context=forks={{.TMP_DIR}}/forks \
                linux/initramfs
          - cmd: xz -k {{.TMP_DIR}}/initramfs.cpio.gz
          - cmd: sha256sum {{.TMP_DIR}}/initramfs.cpio.gz.xz > {{.TMP_DIR}}/initramfs.cpio.gz.xz.sha256
          - cmd: rm {{.TMP_DIR}}/initramfs.cpio.gz
          - cmd: |-
                echo -e "package {{.PACKAGE}}\n\nimport _ \"embed\"\nimport \"github.com/walteh/runm/pkg/binembed\"\n" > {{.TMP_DIR}}/embed.gen.go
                echo -e "//go:embed initramfs.cpio.gz.xz\nvar BinaryXZ []byte\n" >> {{.TMP_DIR}}/embed.gen.go
                echo -e "const BinaryXZChecksum = \"$(cat {{.TMP_DIR}}/initramfs.cpio.gz.xz.sha256 | awk '{print $1}')\"\n" >> {{.TMP_DIR}}/embed.gen.go
                echo -e "func init() {\n\tbinembed.RegisterXZ(BinaryXZChecksum, BinaryXZ)\n}\n" >> {{.TMP_DIR}}/embed.gen.go
          - cmd: go fmt {{.TMP_DIR}}/embed.gen.go
          - cmd: mkdir -p {{.OUT_DIR}}
          - cmd: rm -rf {{.TMP_DIR}}/forks
          - cmd: mv -f {{.TMP_DIR}}/* {{.OUT_DIR}}

    linux:initramfs:
        desc: builds the initramfs
        cmds:
          - for: {var: SUPPORTED_ARCHS}
            task: linux:initramfs:{{.ITEM}}

    linux:vf:*:
        label: 'linux:vf:{{.ARCH}}'
        requires: {vars: [ARCH]}
        desc: builds the vf
        vars:
            ARCH: "{{index .MATCH 0}}"
            KERNEL_DIR: "{{.BUILD_OUT_DIR}}/linux_kernel_{{ .ARCH }}"
            INITRAMFS_DIR: "{{.BUILD_OUT_DIR}}/linux_initramfs_{{ .ARCH }}"
            OUT_DIR: "{{.BUILD_OUT_DIR}}/linux_vf_{{ .ARCH }}"
            TMP_DIR:
                sh: mktemp -d
        cmds:
          - task: linux:kernel:{{.ARCH}}
          - task: linux:initramfs:{{.ARCH}}
          - cmd: mkdir -p {{.TMP_DIR}} {{.OUT_DIR}}
          - defer: rm -rf {{.TMP_DIR}}
          - cmd: cp {{.KERNEL_DIR}}/kernel.xz {{.TMP_DIR}}/kernel.xz
          - cmd: cp {{.INITRAMFS_DIR}}/initramfs.cpio.gz.xz {{.TMP_DIR}}/initramfs.cpio.gz.xz
          - cmd: cp {{.INITRAMFS_DIR}}/mbin.squashfs {{.TMP_DIR}}/mbin.squashfs
          - cmd: unxz {{.TMP_DIR}}/kernel.xz
          - cmd: unxz {{.TMP_DIR}}/initramfs.cpio.gz.xz
          - cmd: mv -f {{.TMP_DIR}}/kernel {{.OUT_DIR}}/kernel
          - cmd: mv -f {{.TMP_DIR}}/initramfs.cpio.gz {{.OUT_DIR}}/initramfs.cpio.gz
          - cmd: mv -f {{.TMP_DIR}}/mbin.squashfs {{.OUT_DIR}}/mbin.squashfs

    linux:all:
        desc: builds all linux components
        cmds:
          - task: linux:kernel
          - task: linux:initramfs

    oci:cache:*:
        label: 'oci:cache:{{.IMAGE}}'
        requires: {vars: [LAYOUTS_DIR, GO_FILE, WRK_DIR, FMT_IMAGE, IMAGE]}
        desc: pulls an oci image and archives it
        vars:
            IMAGE: "{{ index .MATCH 0 }}"
            VAR_NAME: "{{.FMT_IMAGE | upper }}"
            OUT_FILE: "{{.LAYOUTS_DIR}}/{{.FMT_IMAGE}}.tar.gz"
            PLATFORMS:
              - linux/arm64
              - linux/amd64

        cmds:
          - for: {var: PLATFORMS}
            cmd: ./gow tool crane pull --format=oci {{.IMAGE}} {{.WRK_DIR}} --platform {{.ITEM}} --annotate-ref

          - cmd: cd {{.WRK_DIR}} && tar -czf {{.OUT_FILE}} .
            #   - cmd: ./gow run ./cmd/manifest-prune -oci-layout {{.WRK_DIR}}
            #   - cmd: ./gow tool arc archive -f 'tar' -c 'gz' -f '{{.OUT_FILE}}' {{.WRK_DIR}}/*
          - cmd: sha256sum {{.OUT_FILE}} > {{.OUT_FILE}}.sha256
          - cmd: rm -rf {{.WRK_DIR}}
          - cmd: |-
                echo -e "const {{.VAR_NAME }}_TAR_GZ_CHECKSUM = \"$(cat {{.OUT_FILE}}.sha256 | awk '{print $1}')\"" >> {{.GO_FILE}}
                echo -e "const {{.VAR_NAME }} OCICachedImage = \"{{.IMAGE}}\"" >> {{.GO_FILE}}
                echo -e "const {{.VAR_NAME }}_SIZE = \"$(ls -S -lh {{.OUT_FILE}} | awk '{print $5}')\"" >> {{.GO_FILE}}
                echo -e "func init() { register({{.VAR_NAME }}.String(), \"{{.FMT_IMAGE}}.tar.gz\") }\n" >> {{.GO_FILE}}

    oci:cache:
        desc: pulls all oci images and archives them
        vars:
            DIRECTORY: 'gen/oci-image-cache'
            GO_FILE: '{{.DIRECTORY}}/oci_image_cache.gen.go'
            IMAGES:
              - docker.io/library/alpine:latest
              - docker.io/library/busybox:glibc
              - docker.io/library/debian:bookworm-slim
              - docker.io/oven/bun:alpine
              - docker.io/alpine/socat:latest
        cmds:
          - cmd: rm -rf {{.DIRECTORY}}
          - cmd: mkdir -p {{.DIRECTORY}}/layouts
          - cmd: |-
                echo -e "package oci_image_cache\n\n" > {{.GO_FILE}}
                echo -e "import (\n\t\"embed\"\n\t\"github.com/walteh/runm/pkg/testing/toci\"\n)\n" >> {{.GO_FILE}}
                echo -e "type OCICachedImage string\n" >> {{.GO_FILE}}
                echo -e "func (me OCICachedImage) String() string {\n\treturn string(me)\n}\n" >> {{.GO_FILE}}
                echo -e "//go:embed layouts/*\nvar s embed.FS\n\n" >> {{.GO_FILE}}
                echo -e "func register(imageName string, fileName string) {\n\ttoci.MustRegisterImage(imageName, \"layouts/\" + fileName, s)\n}\n" >> {{.GO_FILE}}
          - for: {var: IMAGES}
            task: oci:cache:{{.ITEM}}
            vars:
                LAYOUTS_DIR: {sh: "echo \"$(pwd)/{{.DIRECTORY}}/layouts\""}
                GO_FILE: "{{.GO_FILE}}"
                WRK_DIR: {sh: 'mktemp -d'}
                FMT_IMAGE: |-
                    {{.ITEM | trimPrefix "docker.io/library/" | trimPrefix "docker.io/" | replace "/" "_" | replace ":" "_" | lower | replace "-" "_" | replace "." "_" | replace "+" "_" }}
          - cmd: go fmt {{.DIRECTORY}}/oci_image_cache.gen.go

    dev:shim:killall:
        desc: kills all running containers
        cmds:
          - cmd: sudo -A pkill -f containerd-shim-runc-v2 || true
          - cmd: sudo -A pkill -f nerdctl-test || true
          - cmd: sudo -A killall -9 containerd-shim-runc-v2 || true
          - cmd: sudo -A killall -9 nerdctl-test || true

    dev:2025-06-08:01:
        desc: runs the shim for 2025-06-08
        cmds:
          - task: dev:shim:killall
          - task: harpoon:initramfs:arm64
          - task: harpoon:kernel:arm64
          - cmd: |-
                timeout 20s ./gow -root run -codesign -log-file-to-append-in=.logs/containerd.log ./cmd/nerdctl-dev run \
                    --platform=linux/arm64 \
                    --network=host \
                    --runtime=containerd.shim.harpoon.v2 \
                    --pull=missing \
                    --rm \
                    docker.io/library/alpine:latest \
                    "echo" "-e" "\n\nhi\n\n"
    dev:2025-06-10:01:
        desc: runs the shim for 2025-06-08
        cmds:
          - task: dev:shim:killall
          - task: harpoon:initramfs:arm64
          - task: harpoon:kernel:arm64
          - cmd: |-
                timeout 20s ./gow -root run -codesign -log-file-to-append-in=.logs/containerd.log ./cmd/nerdctl-dev run \
                    --platform=linux/arm64 \
                    --network=host \
                    --runtime=containerd.shim.harpoon.v2 \
                    --pull=missing \
                    --rm \
                    docker.io/oven/bun:alpine \
                    --version

    dev:2025-06-10:02:
        desc: runs the shim for 2025-06-08
        vars:
            TMP_DIR:
                sh: mktemp -d
        cmds:
          - task: dev:shim:killall
          - task: harpoon:initramfs:arm64
          - task: harpoon:kernel:arm64
          - cmd: mkdir -p {{.TMP_DIR}}
          - defer: rm -rf {{.TMP_DIR}}
          - cmd: echo "console.log(new Date().toISOString()); console.log('hi from bun!');" > {{.TMP_DIR}}/script.ts
          - cmd: |-
                timeout 20s ./gow -root run -codesign -log-file-to-append-in=.logs/containerd.log ./cmd/nerdctl-dev run \
                    --platform=linux/arm64 \
                    --network=host \
                    --runtime=containerd.shim.harpoon.v2 \
                    --pull=missing \
                    --rm \
                    --mount=type=bind,src={{.TMP_DIR}},dst=/app/scripts \
                    docker.io/oven/bun:alpine \
                    run /app/scripts/script.ts

    dev:2025-06-08:*:
        label: 'dev:2025-06-08:{{.ARG}}'
        desc: runs the shim for 2025-06-08
        vars:
            ARG: "{{index .MATCH 0}}"
        cmds:
          - cmd: CGO_ENABLED=1 go build -buildmode=plugin -o /tmp/proc-demo/vz-plugin.so ./cmd/plugin-demo/plugin/main.go
          - cmd: ./gow run -codesign ./cmd/proc-demo -{{.ARG}}

    dev:2025-06-18:01:
        desc: runs the shim for 2025-06-08
        env:
            LINUX_RUNTIME_BUILD_DIR:
                sh: realpath ./gen/build/linux_vf_arm64
        cmds:
          - task: dev:shim:killall
          - task: linux:vf:arm64
          - cmd: |-
                timeout 20s sudo -A -E go tool goshim run -codesign -log-file-to-append-in=.logs/containerd.log ./test/integration/cmd/nerdctl-test run \
                    --platform=linux/arm64 \
                    --network=host \
                    --runtime=containerd.shim.runc.v2 \
                    --pull=missing \
                    --rm \
                    docker.io/oven/bun:alpine \
                    --version

    setup:
        desc: sets up the environment
        cmds:
          - task: fork:sync

    fork:sync:
        desc: syncs the forks
        dir: ../
        vars:
            FORKS:
              - branch: main
                repo: "github.com/Code-Hex/vz"

              - branch: main
                repo: "github.com/walteh/containerd"

              - branch: main
                repo: "github.com/walteh/nerdctl"

              - branch: main
                repo: "github.com/walteh/gvisor-tap-vsock"

              - branch: main
                repo: "github.com/walteh/tint"

              - branch: main
                repo: "github.com/walteh/buildkit"

              - branch: main
                repo: "github.com/walteh/ttrpc"

              - branch: main
                repo: "github.com/walteh/nerdctl"

        cmds:
          - for: {var: FORKS}
            cmd: git clone {{.ITEM.repo}} --depth 1 && git fetch origin {{.ITEM.branch}} && git checkout {{.ITEM.branch}}

