// Code generated by options-gen v0.52.1. DO NOT EDIT.

package server

import (
	"github.com/containerd/go-runc"
)

type OptServerSetter func(o *Server)

func NewServer(
	options ...OptServerSetter,
) Server {
	var o Server

	// Setting defaults from field tag (if present)

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithRunc(opt *runc.Runc) OptServerSetter {
	return func(o *Server) { o.runc = opt }
}

func (o *Server) Validate() error {
	return nil
}
