// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/cgroup.proto

package runmv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	anypb "google.golang.org/protobuf/types/known/anypb"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/structpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCgroupStatsRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCgroupStatsRequest) Reset() {
	*x = GetCgroupStatsRequest{}
	mi := &file_v1_cgroup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCgroupStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCgroupStatsRequest) ProtoMessage() {}

func (x *GetCgroupStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cgroup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetCgroupStatsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GetCgroupStatsRequest_builder) Build() *GetCgroupStatsRequest {
	m0 := &GetCgroupStatsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetCgroupStatsResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Stats *anypb.Any             `protobuf:"bytes,1,opt,name=stats"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetCgroupStatsResponse) Reset() {
	*x = GetCgroupStatsResponse{}
	mi := &file_v1_cgroup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCgroupStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCgroupStatsResponse) ProtoMessage() {}

func (x *GetCgroupStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cgroup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetCgroupStatsResponse) GetStats() *anypb.Any {
	if x != nil {
		return x.xxx_hidden_Stats
	}
	return nil
}

func (x *GetCgroupStatsResponse) SetStats(v *anypb.Any) {
	x.xxx_hidden_Stats = v
}

func (x *GetCgroupStatsResponse) HasStats() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Stats != nil
}

func (x *GetCgroupStatsResponse) ClearStats() {
	x.xxx_hidden_Stats = nil
}

type GetCgroupStatsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Stats *anypb.Any
}

func (b0 GetCgroupStatsResponse_builder) Build() *GetCgroupStatsResponse {
	m0 := &GetCgroupStatsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Stats = b.Stats
	return m0
}

type StreamCgroupEventsRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamCgroupEventsRequest) Reset() {
	*x = StreamCgroupEventsRequest{}
	mi := &file_v1_cgroup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamCgroupEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCgroupEventsRequest) ProtoMessage() {}

func (x *StreamCgroupEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cgroup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type StreamCgroupEventsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 StreamCgroupEventsRequest_builder) Build() *StreamCgroupEventsRequest {
	m0 := &StreamCgroupEventsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type CgroupEvent struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Low     uint64                 `protobuf:"varint,1,opt,name=low"`
	xxx_hidden_High    uint64                 `protobuf:"varint,2,opt,name=high"`
	xxx_hidden_Max     uint64                 `protobuf:"varint,3,opt,name=max"`
	xxx_hidden_Oom     uint64                 `protobuf:"varint,4,opt,name=oom"`
	xxx_hidden_OomKill uint64                 `protobuf:"varint,5,opt,name=oom_kill,json=oomKill"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CgroupEvent) Reset() {
	*x = CgroupEvent{}
	mi := &file_v1_cgroup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CgroupEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CgroupEvent) ProtoMessage() {}

func (x *CgroupEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cgroup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CgroupEvent) GetLow() uint64 {
	if x != nil {
		return x.xxx_hidden_Low
	}
	return 0
}

func (x *CgroupEvent) GetHigh() uint64 {
	if x != nil {
		return x.xxx_hidden_High
	}
	return 0
}

func (x *CgroupEvent) GetMax() uint64 {
	if x != nil {
		return x.xxx_hidden_Max
	}
	return 0
}

func (x *CgroupEvent) GetOom() uint64 {
	if x != nil {
		return x.xxx_hidden_Oom
	}
	return 0
}

func (x *CgroupEvent) GetOomKill() uint64 {
	if x != nil {
		return x.xxx_hidden_OomKill
	}
	return 0
}

func (x *CgroupEvent) SetLow(v uint64) {
	x.xxx_hidden_Low = v
}

func (x *CgroupEvent) SetHigh(v uint64) {
	x.xxx_hidden_High = v
}

func (x *CgroupEvent) SetMax(v uint64) {
	x.xxx_hidden_Max = v
}

func (x *CgroupEvent) SetOom(v uint64) {
	x.xxx_hidden_Oom = v
}

func (x *CgroupEvent) SetOomKill(v uint64) {
	x.xxx_hidden_OomKill = v
}

type CgroupEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Low     uint64
	High    uint64
	Max     uint64
	Oom     uint64
	OomKill uint64
}

func (b0 CgroupEvent_builder) Build() *CgroupEvent {
	m0 := &CgroupEvent{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Low = b.Low
	x.xxx_hidden_High = b.High
	x.xxx_hidden_Max = b.Max
	x.xxx_hidden_Oom = b.Oom
	x.xxx_hidden_OomKill = b.OomKill
	return m0
}

type StreamCgroupEventsResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Event *CgroupEvent           `protobuf:"bytes,1,opt,name=event"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StreamCgroupEventsResponse) Reset() {
	*x = StreamCgroupEventsResponse{}
	mi := &file_v1_cgroup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamCgroupEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCgroupEventsResponse) ProtoMessage() {}

func (x *StreamCgroupEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cgroup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StreamCgroupEventsResponse) GetEvent() *CgroupEvent {
	if x != nil {
		return x.xxx_hidden_Event
	}
	return nil
}

func (x *StreamCgroupEventsResponse) SetEvent(v *CgroupEvent) {
	x.xxx_hidden_Event = v
}

func (x *StreamCgroupEventsResponse) HasEvent() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Event != nil
}

func (x *StreamCgroupEventsResponse) ClearEvent() {
	x.xxx_hidden_Event = nil
}

type StreamCgroupEventsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Event *CgroupEvent
}

func (b0 StreamCgroupEventsResponse_builder) Build() *StreamCgroupEventsResponse {
	m0 := &StreamCgroupEventsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Event = b.Event
	return m0
}

type ToggleAllControllersRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleAllControllersRequest) Reset() {
	*x = ToggleAllControllersRequest{}
	mi := &file_v1_cgroup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleAllControllersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleAllControllersRequest) ProtoMessage() {}

func (x *ToggleAllControllersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cgroup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ToggleAllControllersRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ToggleAllControllersRequest_builder) Build() *ToggleAllControllersRequest {
	m0 := &ToggleAllControllersRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ToggleAllControllersResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleAllControllersResponse) Reset() {
	*x = ToggleAllControllersResponse{}
	mi := &file_v1_cgroup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleAllControllersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleAllControllersResponse) ProtoMessage() {}

func (x *ToggleAllControllersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cgroup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ToggleAllControllersResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ToggleAllControllersResponse_builder) Build() *ToggleAllControllersResponse {
	m0 := &ToggleAllControllersResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_v1_cgroup_proto protoreflect.FileDescriptor

const file_v1_cgroup_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/cgroup.proto\x12\arunm.v1\x1a\x1bbuf/validate/validate.proto\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a!google/protobuf/go_features.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x17\n" +
	"\x15GetCgroupStatsRequest\"D\n" +
	"\x16GetCgroupStatsResponse\x12*\n" +
	"\x05stats\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x05stats\"\x1b\n" +
	"\x19StreamCgroupEventsRequest\"r\n" +
	"\vCgroupEvent\x12\x10\n" +
	"\x03low\x18\x01 \x01(\x04R\x03low\x12\x12\n" +
	"\x04high\x18\x02 \x01(\x04R\x04high\x12\x10\n" +
	"\x03max\x18\x03 \x01(\x04R\x03max\x12\x10\n" +
	"\x03oom\x18\x04 \x01(\x04R\x03oom\x12\x19\n" +
	"\boom_kill\x18\x05 \x01(\x04R\aoomKill\"H\n" +
	"\x1aStreamCgroupEventsResponse\x12*\n" +
	"\x05event\x18\x01 \x01(\v2\x14.runm.v1.CgroupEventR\x05event\"\x1d\n" +
	"\x1bToggleAllControllersRequest\"\x1e\n" +
	"\x1cToggleAllControllersResponse2\xaf\x02\n" +
	"\x14CgroupAdapterService\x12Q\n" +
	"\x0eGetCgroupStats\x12\x1e.runm.v1.GetCgroupStatsRequest\x1a\x1f.runm.v1.GetCgroupStatsResponse\x12_\n" +
	"\x12StreamCgroupEvents\x12\".runm.v1.StreamCgroupEventsRequest\x1a#.runm.v1.StreamCgroupEventsResponse0\x01\x12c\n" +
	"\x14ToggleAllControllers\x12$.runm.v1.ToggleAllControllersRequest\x1a%.runm.v1.ToggleAllControllersResponseB\x89\x01\n" +
	"\vcom.runm.v1B\vCgroupProtoP\x01Z&github.com/walteh/runm/proto/v1;runmv1\xa2\x02\x03RXX\xaa\x02\aRunm.V1\xca\x02\aRunm\\V1\xe2\x02\x13Runm\\V1\\GPBMetadata\xea\x02\bRunm::V1\x92\x03\a\xd2>\x02\x10\x03\b\x02b\beditionsp\xe8\a"

var file_v1_cgroup_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_v1_cgroup_proto_goTypes = []any{
	(*GetCgroupStatsRequest)(nil),        // 0: runm.v1.GetCgroupStatsRequest
	(*GetCgroupStatsResponse)(nil),       // 1: runm.v1.GetCgroupStatsResponse
	(*StreamCgroupEventsRequest)(nil),    // 2: runm.v1.StreamCgroupEventsRequest
	(*CgroupEvent)(nil),                  // 3: runm.v1.CgroupEvent
	(*StreamCgroupEventsResponse)(nil),   // 4: runm.v1.StreamCgroupEventsResponse
	(*ToggleAllControllersRequest)(nil),  // 5: runm.v1.ToggleAllControllersRequest
	(*ToggleAllControllersResponse)(nil), // 6: runm.v1.ToggleAllControllersResponse
	(*anypb.Any)(nil),                    // 7: google.protobuf.Any
}
var file_v1_cgroup_proto_depIdxs = []int32{
	7, // 0: runm.v1.GetCgroupStatsResponse.stats:type_name -> google.protobuf.Any
	3, // 1: runm.v1.StreamCgroupEventsResponse.event:type_name -> runm.v1.CgroupEvent
	0, // 2: runm.v1.CgroupAdapterService.GetCgroupStats:input_type -> runm.v1.GetCgroupStatsRequest
	2, // 3: runm.v1.CgroupAdapterService.StreamCgroupEvents:input_type -> runm.v1.StreamCgroupEventsRequest
	5, // 4: runm.v1.CgroupAdapterService.ToggleAllControllers:input_type -> runm.v1.ToggleAllControllersRequest
	1, // 5: runm.v1.CgroupAdapterService.GetCgroupStats:output_type -> runm.v1.GetCgroupStatsResponse
	4, // 6: runm.v1.CgroupAdapterService.StreamCgroupEvents:output_type -> runm.v1.StreamCgroupEventsResponse
	6, // 7: runm.v1.CgroupAdapterService.ToggleAllControllers:output_type -> runm.v1.ToggleAllControllersResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_cgroup_proto_init() }
func file_v1_cgroup_proto_init() {
	if File_v1_cgroup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_cgroup_proto_rawDesc), len(file_v1_cgroup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_cgroup_proto_goTypes,
		DependencyIndexes: file_v1_cgroup_proto_depIdxs,
		MessageInfos:      file_v1_cgroup_proto_msgTypes,
	}.Build()
	File_v1_cgroup_proto = out.File
	file_v1_cgroup_proto_goTypes = nil
	file_v1_cgroup_proto_depIdxs = nil
}
