// Code generated by protoc-gen-go-ttrpc. DO NOT EDIT.
// source: v1/cgroup.proto
package runmv1

import (
	context "context"
	ttrpc "github.com/containerd/ttrpc"
)

type TTRPCCgroupAdapterServiceService interface {
	GetCgroupStats(context.Context, *GetCgroupStatsRequest) (*GetCgroupStatsResponse, error)
	StreamCgroupEvents(context.Context, *StreamCgroupEventsRequest, TTRPCCgroupAdapterService_StreamCgroupEventsServer) error
	ToggleAllControllers(context.Context, *ToggleAllControllersRequest) (*ToggleAllControllersResponse, error)
}

type TTRPCCgroupAdapterService_StreamCgroupEventsServer interface {
	Send(*StreamCgroupEventsResponse) error
	ttrpc.StreamServer
}

type ttrpccgroupadapterserviceStreamCgroupEventsServer struct {
	ttrpc.StreamServer
}

func (x *ttrpccgroupadapterserviceStreamCgroupEventsServer) Send(m *StreamCgroupEventsResponse) error {
	return x.StreamServer.SendMsg(m)
}

func RegisterTTRPCCgroupAdapterServiceService(srv *ttrpc.Server, svc TTRPCCgroupAdapterServiceService) {
	srv.RegisterService("runm.v1.CgroupAdapterService", &ttrpc.ServiceDesc{
		Methods: map[string]ttrpc.Method{
			"GetCgroupStats": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req GetCgroupStatsRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.GetCgroupStats(ctx, &req)
			},
			"ToggleAllControllers": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req ToggleAllControllersRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.ToggleAllControllers(ctx, &req)
			},
		},
		Streams: map[string]ttrpc.Stream{
			"StreamCgroupEvents": {
				Handler: func(ctx context.Context, stream ttrpc.StreamServer) (interface{}, error) {
					m := new(StreamCgroupEventsRequest)
					if err := stream.RecvMsg(m); err != nil {
						return nil, err
					}
					return nil, svc.StreamCgroupEvents(ctx, m, &ttrpccgroupadapterserviceStreamCgroupEventsServer{stream})
				},
				StreamingClient: false,
				StreamingServer: true,
			},
		},
	})
}

type TTRPCCgroupAdapterServiceClient interface {
	GetCgroupStats(context.Context, *GetCgroupStatsRequest) (*GetCgroupStatsResponse, error)
	StreamCgroupEvents(context.Context, *StreamCgroupEventsRequest) (TTRPCCgroupAdapterService_StreamCgroupEventsClient, error)
	ToggleAllControllers(context.Context, *ToggleAllControllersRequest) (*ToggleAllControllersResponse, error)
}

type ttrpccgroupadapterserviceClient struct {
	client *ttrpc.Client
}

func NewTTRPCCgroupAdapterServiceClient(client *ttrpc.Client) TTRPCCgroupAdapterServiceClient {
	return &ttrpccgroupadapterserviceClient{
		client: client,
	}
}

func (c *ttrpccgroupadapterserviceClient) GetCgroupStats(ctx context.Context, req *GetCgroupStatsRequest) (*GetCgroupStatsResponse, error) {
	var resp GetCgroupStatsResponse
	if err := c.client.Call(ctx, "runm.v1.CgroupAdapterService", "GetCgroupStats", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *ttrpccgroupadapterserviceClient) StreamCgroupEvents(ctx context.Context, req *StreamCgroupEventsRequest) (TTRPCCgroupAdapterService_StreamCgroupEventsClient, error) {
	stream, err := c.client.NewStream(ctx, &ttrpc.StreamDesc{
		StreamingClient: false,
		StreamingServer: true,
	}, "runm.v1.CgroupAdapterService", "StreamCgroupEvents", req)
	if err != nil {
		return nil, err
	}
	x := &ttrpccgroupadapterserviceStreamCgroupEventsClient{stream}
	return x, nil
}

type TTRPCCgroupAdapterService_StreamCgroupEventsClient interface {
	Recv() (*StreamCgroupEventsResponse, error)
	ttrpc.ClientStream
}

type ttrpccgroupadapterserviceStreamCgroupEventsClient struct {
	ttrpc.ClientStream
}

func (x *ttrpccgroupadapterserviceStreamCgroupEventsClient) Recv() (*StreamCgroupEventsResponse, error) {
	m := new(StreamCgroupEventsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ttrpccgroupadapterserviceClient) ToggleAllControllers(ctx context.Context, req *ToggleAllControllersRequest) (*ToggleAllControllersResponse, error) {
	var resp ToggleAllControllersResponse
	if err := c.client.Call(ctx, "runm.v1.CgroupAdapterService", "ToggleAllControllers", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
