// Code generated by protoc-gen-go-opaque-helpers. DO NOT EDIT.
// source: v1/console.proto

package runvv1

import (
	protovalidate "buf.build/go/protovalidate"
)

// ptr is a helper function to get a pointer to a value
func ptr[T any](v T) *T { return &v }

// NewPollRequest creates a new PollRequest using the builder pattern
func NewPollRequest(f func(*PollRequest_builder)) *PollRequest {
	b := &PollRequest_builder{}
	f(b)
	return b.Build()
}

// NewPollRequestE creates a new PollRequest using the builder pattern with validation
func NewPollRequestE(f func(*PollRequest_builder)) (*PollRequest, error) {
	m := NewPollRequest(f)
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NewPollResponse creates a new PollResponse using the builder pattern
func NewPollResponse(f func(*PollResponse_builder)) *PollResponse {
	b := &PollResponse_builder{}
	f(b)
	return b.Build()
}

// NewPollResponseE creates a new PollResponse using the builder pattern with validation
func NewPollResponseE(f func(*PollResponse_builder)) (*PollResponse, error) {
	m := NewPollResponse(f)
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}
