// Code generated by protoc-gen-slog-valuer. DO NOT EDIT.
//
// source: v1/event.proto

package runmv1

import (
	slog "log/slog"
)

func (x *ReceiveEventsRequest) LogValue() slog.Value {
	if x == nil {
		return slog.AnyValue(nil)
	}
	attrs := make([]slog.Attr, 0, 0)
	return slog.GroupValue(attrs...)
}

func (x *PublishEventRequest) LogValue() slog.Value {
	if x == nil {
		return slog.AnyValue(nil)
	}
	attrs := make([]slog.Attr, 0, 2)
	attrs = append(attrs, slog.String("topic", x.GetTopic()))
	attrs = append(attrs, slog.Any("raw_json", x.GetRawJson()))
	return slog.GroupValue(attrs...)
}

func (x *PublishEventResponse) LogValue() slog.Value {
	if x == nil {
		return slog.AnyValue(nil)
	}
	attrs := make([]slog.Attr, 0, 0)
	return slog.GroupValue(attrs...)
}

func (x *PublishEventsResponse) LogValue() slog.Value {
	if x == nil {
		return slog.AnyValue(nil)
	}
	attrs := make([]slog.Attr, 0, 2)
	attrs = append(attrs, slog.String("topic", x.GetTopic()))
	attrs = append(attrs, slog.Any("raw_json", x.GetRawJson()))
	return slog.GroupValue(attrs...)
}
