// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/management.proto

package runmv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GuestTimeSyncRequest struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UnixTimeNs uint64                 `protobuf:"varint,1,opt,name=unix_time_ns,json=unixTimeNs"`
	xxx_hidden_Timezone   string                 `protobuf:"bytes,2,opt,name=timezone"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GuestTimeSyncRequest) Reset() {
	*x = GuestTimeSyncRequest{}
	mi := &file_v1_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuestTimeSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestTimeSyncRequest) ProtoMessage() {}

func (x *GuestTimeSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GuestTimeSyncRequest) GetUnixTimeNs() uint64 {
	if x != nil {
		return x.xxx_hidden_UnixTimeNs
	}
	return 0
}

func (x *GuestTimeSyncRequest) GetTimezone() string {
	if x != nil {
		return x.xxx_hidden_Timezone
	}
	return ""
}

func (x *GuestTimeSyncRequest) SetUnixTimeNs(v uint64) {
	x.xxx_hidden_UnixTimeNs = v
}

func (x *GuestTimeSyncRequest) SetTimezone(v string) {
	x.xxx_hidden_Timezone = v
}

type GuestTimeSyncRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UnixTimeNs uint64
	Timezone   string
}

func (b0 GuestTimeSyncRequest_builder) Build() *GuestTimeSyncRequest {
	m0 := &GuestTimeSyncRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_UnixTimeNs = b.UnixTimeNs
	x.xxx_hidden_Timezone = b.Timezone
	return m0
}

type GuestTimeSyncResponse struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PreviousTimeNs uint64                 `protobuf:"varint,1,opt,name=previous_time_ns,json=previousTimeNs"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *GuestTimeSyncResponse) Reset() {
	*x = GuestTimeSyncResponse{}
	mi := &file_v1_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuestTimeSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestTimeSyncResponse) ProtoMessage() {}

func (x *GuestTimeSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GuestTimeSyncResponse) GetPreviousTimeNs() uint64 {
	if x != nil {
		return x.xxx_hidden_PreviousTimeNs
	}
	return 0
}

func (x *GuestTimeSyncResponse) SetPreviousTimeNs(v uint64) {
	x.xxx_hidden_PreviousTimeNs = v
}

type GuestTimeSyncResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PreviousTimeNs uint64
}

func (b0 GuestTimeSyncResponse_builder) Build() *GuestTimeSyncResponse {
	m0 := &GuestTimeSyncResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_PreviousTimeNs = b.PreviousTimeNs
	return m0
}

type GuestReadinessRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuestReadinessRequest) Reset() {
	*x = GuestReadinessRequest{}
	mi := &file_v1_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuestReadinessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestReadinessRequest) ProtoMessage() {}

func (x *GuestReadinessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GuestReadinessRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GuestReadinessRequest_builder) Build() *GuestReadinessRequest {
	m0 := &GuestReadinessRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GuestReadinessResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ready bool                   `protobuf:"varint,1,opt,name=ready"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GuestReadinessResponse) Reset() {
	*x = GuestReadinessResponse{}
	mi := &file_v1_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuestReadinessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestReadinessResponse) ProtoMessage() {}

func (x *GuestReadinessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GuestReadinessResponse) GetReady() bool {
	if x != nil {
		return x.xxx_hidden_Ready
	}
	return false
}

func (x *GuestReadinessResponse) SetReady(v bool) {
	x.xxx_hidden_Ready = v
}

type GuestReadinessResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ready bool
}

func (b0 GuestReadinessResponse_builder) Build() *GuestReadinessResponse {
	m0 := &GuestReadinessResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ready = b.Ready
	return m0
}

type GuestRunCommandRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Stdin   []byte                 `protobuf:"bytes,1,opt,name=stdin"`
	xxx_hidden_Argc    string                 `protobuf:"bytes,2,opt,name=argc"`
	xxx_hidden_Argv    []string               `protobuf:"bytes,3,rep,name=argv"`
	xxx_hidden_EnvVars map[string]string      `protobuf:"bytes,4,rep,name=env_vars,json=envVars" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Chroot  string                 `protobuf:"bytes,5,opt,name=chroot"`
	xxx_hidden_Cwd     []byte                 `protobuf:"bytes,6,opt,name=cwd"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GuestRunCommandRequest) Reset() {
	*x = GuestRunCommandRequest{}
	mi := &file_v1_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuestRunCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestRunCommandRequest) ProtoMessage() {}

func (x *GuestRunCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GuestRunCommandRequest) GetStdin() []byte {
	if x != nil {
		return x.xxx_hidden_Stdin
	}
	return nil
}

func (x *GuestRunCommandRequest) GetArgc() string {
	if x != nil {
		return x.xxx_hidden_Argc
	}
	return ""
}

func (x *GuestRunCommandRequest) GetArgv() []string {
	if x != nil {
		return x.xxx_hidden_Argv
	}
	return nil
}

func (x *GuestRunCommandRequest) GetEnvVars() map[string]string {
	if x != nil {
		return x.xxx_hidden_EnvVars
	}
	return nil
}

func (x *GuestRunCommandRequest) GetChroot() string {
	if x != nil {
		return x.xxx_hidden_Chroot
	}
	return ""
}

func (x *GuestRunCommandRequest) GetCwd() []byte {
	if x != nil {
		return x.xxx_hidden_Cwd
	}
	return nil
}

func (x *GuestRunCommandRequest) SetStdin(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Stdin = v
}

func (x *GuestRunCommandRequest) SetArgc(v string) {
	x.xxx_hidden_Argc = v
}

func (x *GuestRunCommandRequest) SetArgv(v []string) {
	x.xxx_hidden_Argv = v
}

func (x *GuestRunCommandRequest) SetEnvVars(v map[string]string) {
	x.xxx_hidden_EnvVars = v
}

func (x *GuestRunCommandRequest) SetChroot(v string) {
	x.xxx_hidden_Chroot = v
}

func (x *GuestRunCommandRequest) SetCwd(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Cwd = v
}

type GuestRunCommandRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Stdin []byte
	// the executable to run
	Argc string
	// the arguments to pass to the executable
	Argv []string
	// the environment variables to set for the executable
	EnvVars map[string]string
	Chroot  string
	Cwd     []byte
}

func (b0 GuestRunCommandRequest_builder) Build() *GuestRunCommandRequest {
	m0 := &GuestRunCommandRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Stdin = b.Stdin
	x.xxx_hidden_Argc = b.Argc
	x.xxx_hidden_Argv = b.Argv
	x.xxx_hidden_EnvVars = b.EnvVars
	x.xxx_hidden_Chroot = b.Chroot
	x.xxx_hidden_Cwd = b.Cwd
	return m0
}

type GuestRunCommandResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Stdout   []byte                 `protobuf:"bytes,1,opt,name=stdout"`
	xxx_hidden_Stderr   []byte                 `protobuf:"bytes,2,opt,name=stderr"`
	xxx_hidden_ExitCode int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GuestRunCommandResponse) Reset() {
	*x = GuestRunCommandResponse{}
	mi := &file_v1_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuestRunCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestRunCommandResponse) ProtoMessage() {}

func (x *GuestRunCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GuestRunCommandResponse) GetStdout() []byte {
	if x != nil {
		return x.xxx_hidden_Stdout
	}
	return nil
}

func (x *GuestRunCommandResponse) GetStderr() []byte {
	if x != nil {
		return x.xxx_hidden_Stderr
	}
	return nil
}

func (x *GuestRunCommandResponse) GetExitCode() int32 {
	if x != nil {
		return x.xxx_hidden_ExitCode
	}
	return 0
}

func (x *GuestRunCommandResponse) SetStdout(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Stdout = v
}

func (x *GuestRunCommandResponse) SetStderr(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Stderr = v
}

func (x *GuestRunCommandResponse) SetExitCode(v int32) {
	x.xxx_hidden_ExitCode = v
}

type GuestRunCommandResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Stdout   []byte
	Stderr   []byte
	ExitCode int32
}

func (b0 GuestRunCommandResponse_builder) Build() *GuestRunCommandResponse {
	m0 := &GuestRunCommandResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Stdout = b.Stdout
	x.xxx_hidden_Stderr = b.Stderr
	x.xxx_hidden_ExitCode = b.ExitCode
	return m0
}

var File_v1_management_proto protoreflect.FileDescriptor

const file_v1_management_proto_rawDesc = "" +
	"\n" +
	"\x13v1/management.proto\x12\arunm.v1\x1a\x1bbuf/validate/validate.proto\x1a!google/protobuf/go_features.proto\"d\n" +
	"\x14GuestTimeSyncRequest\x12(\n" +
	"\funix_time_ns\x18\x01 \x01(\x04B\x06\xbaH\x03\xc8\x01\x01R\n" +
	"unixTimeNs\x12\"\n" +
	"\btimezone\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\btimezone\"I\n" +
	"\x15GuestTimeSyncResponse\x120\n" +
	"\x10previous_time_ns\x18\x01 \x01(\x04B\x06\xbaH\x03\xc8\x01\x01R\x0epreviousTimeNs\"\x17\n" +
	"\x15GuestReadinessRequest\"6\n" +
	"\x16GuestReadinessResponse\x12\x1c\n" +
	"\x05ready\x18\x01 \x01(\bB\x06\xbaH\x03\xc8\x01\x01R\x05ready\"\xb5\x02\n" +
	"\x16GuestRunCommandRequest\x12\x1c\n" +
	"\x05stdin\x18\x01 \x01(\fB\x06\xbaH\x03\xc8\x01\x00R\x05stdin\x12\x1a\n" +
	"\x04argc\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04argc\x12\x1a\n" +
	"\x04argv\x18\x03 \x03(\tB\x06\xbaH\x03\xc8\x01\x01R\x04argv\x12O\n" +
	"\benv_vars\x18\x04 \x03(\v2,.runm.v1.GuestRunCommandRequest.EnvVarsEntryB\x06\xbaH\x03\xc8\x01\x01R\aenvVars\x12\x1e\n" +
	"\x06chroot\x18\x05 \x01(\tB\x06\xbaH\x03\xc8\x01\x00R\x06chroot\x12\x18\n" +
	"\x03cwd\x18\x06 \x01(\fB\x06\xbaH\x03\xc8\x01\x00R\x03cwd\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"~\n" +
	"\x17GuestRunCommandResponse\x12\x1e\n" +
	"\x06stdout\x18\x01 \x01(\fB\x06\xbaH\x03\xc8\x01\x00R\x06stdout\x12\x1e\n" +
	"\x06stderr\x18\x02 \x01(\fB\x06\xbaH\x03\xc8\x01\x00R\x06stderr\x12#\n" +
	"\texit_code\x18\x03 \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\bexitCode2\x91\x02\n" +
	"\x16GuestManagementService\x12N\n" +
	"\rGuestTimeSync\x12\x1d.runm.v1.GuestTimeSyncRequest\x1a\x1e.runm.v1.GuestTimeSyncResponse\x12Q\n" +
	"\x0eGuestReadiness\x12\x1e.runm.v1.GuestReadinessRequest\x1a\x1f.runm.v1.GuestReadinessResponse\x12T\n" +
	"\x0fGuestRunCommand\x12\x1f.runm.v1.GuestRunCommandRequest\x1a .runm.v1.GuestRunCommandResponseB\x8d\x01\n" +
	"\vcom.runm.v1B\x0fManagementProtoP\x01Z&github.com/walteh/runm/proto/v1;runmv1\xa2\x02\x03RXX\xaa\x02\aRunm.V1\xca\x02\aRunm\\V1\xe2\x02\x13Runm\\V1\\GPBMetadata\xea\x02\bRunm::V1\x92\x03\a\xd2>\x02\x10\x03\b\x02b\beditionsp\xe8\a"

var file_v1_management_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_v1_management_proto_goTypes = []any{
	(*GuestTimeSyncRequest)(nil),    // 0: runm.v1.GuestTimeSyncRequest
	(*GuestTimeSyncResponse)(nil),   // 1: runm.v1.GuestTimeSyncResponse
	(*GuestReadinessRequest)(nil),   // 2: runm.v1.GuestReadinessRequest
	(*GuestReadinessResponse)(nil),  // 3: runm.v1.GuestReadinessResponse
	(*GuestRunCommandRequest)(nil),  // 4: runm.v1.GuestRunCommandRequest
	(*GuestRunCommandResponse)(nil), // 5: runm.v1.GuestRunCommandResponse
	nil,                             // 6: runm.v1.GuestRunCommandRequest.EnvVarsEntry
}
var file_v1_management_proto_depIdxs = []int32{
	6, // 0: runm.v1.GuestRunCommandRequest.env_vars:type_name -> runm.v1.GuestRunCommandRequest.EnvVarsEntry
	0, // 1: runm.v1.GuestManagementService.GuestTimeSync:input_type -> runm.v1.GuestTimeSyncRequest
	2, // 2: runm.v1.GuestManagementService.GuestReadiness:input_type -> runm.v1.GuestReadinessRequest
	4, // 3: runm.v1.GuestManagementService.GuestRunCommand:input_type -> runm.v1.GuestRunCommandRequest
	1, // 4: runm.v1.GuestManagementService.GuestTimeSync:output_type -> runm.v1.GuestTimeSyncResponse
	3, // 5: runm.v1.GuestManagementService.GuestReadiness:output_type -> runm.v1.GuestReadinessResponse
	5, // 6: runm.v1.GuestManagementService.GuestRunCommand:output_type -> runm.v1.GuestRunCommandResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_management_proto_init() }
func file_v1_management_proto_init() {
	if File_v1_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_management_proto_rawDesc), len(file_v1_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_management_proto_goTypes,
		DependencyIndexes: file_v1_management_proto_depIdxs,
		MessageInfos:      file_v1_management_proto_msgTypes,
	}.Build()
	File_v1_management_proto = out.File
	file_v1_management_proto_goTypes = nil
	file_v1_management_proto_depIdxs = nil
}
