// Code generated by protoc-gen-go-opaque-helpers. DO NOT EDIT.
// source: v1/prctl.proto

package runvv1

import (
	protovalidate "buf.build/go/protovalidate"
)

// NewCreateRequest creates a new CreateRequest using the builder
func NewCreateRequest(b *CreateRequest_builder) *CreateRequest {
	return b.Build()
}

// NewCreateRequestE creates a new CreateRequest using the builder with validation
func NewCreateRequestE(b *CreateRequest_builder) (*CreateRequest, error) {
	m := b.Build()
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NewCreateResponse creates a new CreateResponse using the builder
func NewCreateResponse(b *CreateResponse_builder) *CreateResponse {
	return b.Build()
}

// NewCreateResponseE creates a new CreateResponse using the builder with validation
func NewCreateResponseE(b *CreateResponse_builder) (*CreateResponse, error) {
	m := b.Build()
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NewShareFromRequest creates a new ShareFromRequest using the builder
func NewShareFromRequest(b *ShareFromRequest_builder) *ShareFromRequest {
	return b.Build()
}

// NewShareFromRequestE creates a new ShareFromRequest using the builder with validation
func NewShareFromRequestE(b *ShareFromRequest_builder) (*ShareFromRequest, error) {
	m := b.Build()
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NewShareFromResponse creates a new ShareFromResponse using the builder
func NewShareFromResponse(b *ShareFromResponse_builder) *ShareFromResponse {
	return b.Build()
}

// NewShareFromResponseE creates a new ShareFromResponse using the builder with validation
func NewShareFromResponseE(b *ShareFromResponse_builder) (*ShareFromResponse, error) {
	m := b.Build()
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}
