// Code generated by protoc-gen-go-opaque-helpers. DO NOT EDIT.
// source: v1/prctl.proto

package runvv1

import (
	protovalidate "buf.build/go/protovalidate"
)

// NewCreateRequest creates a new CreateRequest using the builder pattern
func NewCreateRequest(f func(*CreateRequest_builder)) *CreateRequest {
	b := &CreateRequest_builder{}
	f(b)
	return b.Build()
}

// NewCreateRequestE creates a new CreateRequest using the builder pattern with validation
func NewCreateRequestE(f func(*CreateRequest_builder)) (*CreateRequest, error) {
	m := NewCreateRequest(f)
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NewCreateResponse creates a new CreateResponse using the builder pattern
func NewCreateResponse(f func(*CreateResponse_builder)) *CreateResponse {
	b := &CreateResponse_builder{}
	f(b)
	return b.Build()
}

// NewCreateResponseE creates a new CreateResponse using the builder pattern with validation
func NewCreateResponseE(f func(*CreateResponse_builder)) (*CreateResponse, error) {
	m := NewCreateResponse(f)
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NewShareFromRequest creates a new ShareFromRequest using the builder pattern
func NewShareFromRequest(f func(*ShareFromRequest_builder)) *ShareFromRequest {
	b := &ShareFromRequest_builder{}
	f(b)
	return b.Build()
}

// NewShareFromRequestE creates a new ShareFromRequest using the builder pattern with validation
func NewShareFromRequestE(f func(*ShareFromRequest_builder)) (*ShareFromRequest, error) {
	m := NewShareFromRequest(f)
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NewShareFromResponse creates a new ShareFromResponse using the builder pattern
func NewShareFromResponse(f func(*ShareFromResponse_builder)) *ShareFromResponse {
	b := &ShareFromResponse_builder{}
	f(b)
	return b.Build()
}

// NewShareFromResponseE creates a new ShareFromResponse using the builder pattern with validation
func NewShareFromResponseE(f func(*ShareFromResponse_builder)) (*ShareFromResponse, error) {
	m := NewShareFromResponse(f)
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}
