// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: v1/runc.proto

package runvv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RuncService_Ping_FullMethodName = "/runv.v1.RuncService/Ping"
)

// RuncServiceClient is the client API for RuncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RuncServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type runcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRuncServiceClient(cc grpc.ClientConnInterface) RuncServiceClient {
	return &runcServiceClient{cc}
}

func (c *runcServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, RuncService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuncServiceServer is the server API for RuncService service.
// All implementations must embed UnimplementedRuncServiceServer
// for forward compatibility.
type RuncServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedRuncServiceServer()
}

// UnimplementedRuncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuncServiceServer struct{}

func (UnimplementedRuncServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedRuncServiceServer) mustEmbedUnimplementedRuncServiceServer() {}
func (UnimplementedRuncServiceServer) testEmbeddedByValue()                     {}

// UnsafeRuncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuncServiceServer will
// result in compilation errors.
type UnsafeRuncServiceServer interface {
	mustEmbedUnimplementedRuncServiceServer()
}

func RegisterRuncServiceServer(s grpc.ServiceRegistrar, srv RuncServiceServer) {
	// If the following call pancis, it indicates UnimplementedRuncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RuncService_ServiceDesc, srv)
}

func _RuncService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuncServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuncService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuncServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RuncService_ServiceDesc is the grpc.ServiceDesc for RuncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runv.v1.RuncService",
	HandlerType: (*RuncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _RuncService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/runc.proto",
}
