// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: v1/runc.proto

package runvv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RuncService_Ping_FullMethodName                 = "/runv.v1.RuncService/Ping"
	RuncService_Create_FullMethodName               = "/runv.v1.RuncService/Create"
	RuncService_Start_FullMethodName                = "/runv.v1.RuncService/Start"
	RuncService_Exec_FullMethodName                 = "/runv.v1.RuncService/Exec"
	RuncService_Delete_FullMethodName               = "/runv.v1.RuncService/Delete"
	RuncService_Kill_FullMethodName                 = "/runv.v1.RuncService/Kill"
	RuncService_Pause_FullMethodName                = "/runv.v1.RuncService/Pause"
	RuncService_Resume_FullMethodName               = "/runv.v1.RuncService/Resume"
	RuncService_Ps_FullMethodName                   = "/runv.v1.RuncService/Ps"
	RuncService_Checkpoint_FullMethodName           = "/runv.v1.RuncService/Checkpoint"
	RuncService_Restore_FullMethodName              = "/runv.v1.RuncService/Restore"
	RuncService_Update_FullMethodName               = "/runv.v1.RuncService/Update"
	RuncService_NewTempConsoleSocket_FullMethodName = "/runv.v1.RuncService/NewTempConsoleSocket"
	RuncService_ReadPidFile_FullMethodName          = "/runv.v1.RuncService/ReadPidFile"
)

// RuncServiceClient is the client API for RuncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RuncServiceClient interface {
	// Ping checks if the service is alive
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// Create creates a new container
	Create(ctx context.Context, in *RuncCreateRequest, opts ...grpc.CallOption) (*RuncCreateResponse, error)
	// Start will start an already created container
	Start(ctx context.Context, in *RuncStartRequest, opts ...grpc.CallOption) (*RuncStartResponse, error)
	// Exec executes an additional process inside the container
	Exec(ctx context.Context, in *RuncExecRequest, opts ...grpc.CallOption) (*RuncExecResponse, error)
	// Delete deletes the container
	Delete(ctx context.Context, in *RuncDeleteRequest, opts ...grpc.CallOption) (*RuncDeleteResponse, error)
	// Kill sends the specified signal to the container
	Kill(ctx context.Context, in *RuncKillRequest, opts ...grpc.CallOption) (*RuncKillResponse, error)
	// Pause the container with the provided id
	Pause(ctx context.Context, in *RuncPauseRequest, opts ...grpc.CallOption) (*RuncPauseResponse, error)
	// Resume the container with the provided id
	Resume(ctx context.Context, in *RuncResumeRequest, opts ...grpc.CallOption) (*RuncResumeResponse, error)
	// Ps lists all the processes inside the container returning their pids
	Ps(ctx context.Context, in *RuncPsRequest, opts ...grpc.CallOption) (*RuncPsResponse, error)
	// Checkpoint checkpoints the container
	Checkpoint(ctx context.Context, in *RuncCheckpointRequest, opts ...grpc.CallOption) (*RuncCheckpointResponse, error)
	// Restore restores the container from a checkpoint
	Restore(ctx context.Context, in *RuncRestoreRequest, opts ...grpc.CallOption) (*RuncRestoreResponse, error)
	// Update updates the container resources
	Update(ctx context.Context, in *RuncUpdateRequest, opts ...grpc.CallOption) (*RuncUpdateResponse, error)
	NewTempConsoleSocket(ctx context.Context, in *RuncNewTempConsoleSocketRequest, opts ...grpc.CallOption) (*RuncNewTempConsoleSocketResponse, error)
	ReadPidFile(ctx context.Context, in *RuncReadPidFileRequest, opts ...grpc.CallOption) (*RuncReadPidFileResponse, error)
}

type runcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRuncServiceClient(cc grpc.ClientConnInterface) RuncServiceClient {
	return &runcServiceClient{cc}
}

func (c *runcServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, RuncService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runcServiceClient) Create(ctx context.Context, in *RuncCreateRequest, opts ...grpc.CallOption) (*RuncCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuncCreateResponse)
	err := c.cc.Invoke(ctx, RuncService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runcServiceClient) Start(ctx context.Context, in *RuncStartRequest, opts ...grpc.CallOption) (*RuncStartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuncStartResponse)
	err := c.cc.Invoke(ctx, RuncService_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runcServiceClient) Exec(ctx context.Context, in *RuncExecRequest, opts ...grpc.CallOption) (*RuncExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuncExecResponse)
	err := c.cc.Invoke(ctx, RuncService_Exec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runcServiceClient) Delete(ctx context.Context, in *RuncDeleteRequest, opts ...grpc.CallOption) (*RuncDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuncDeleteResponse)
	err := c.cc.Invoke(ctx, RuncService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runcServiceClient) Kill(ctx context.Context, in *RuncKillRequest, opts ...grpc.CallOption) (*RuncKillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuncKillResponse)
	err := c.cc.Invoke(ctx, RuncService_Kill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runcServiceClient) Pause(ctx context.Context, in *RuncPauseRequest, opts ...grpc.CallOption) (*RuncPauseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuncPauseResponse)
	err := c.cc.Invoke(ctx, RuncService_Pause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runcServiceClient) Resume(ctx context.Context, in *RuncResumeRequest, opts ...grpc.CallOption) (*RuncResumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuncResumeResponse)
	err := c.cc.Invoke(ctx, RuncService_Resume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runcServiceClient) Ps(ctx context.Context, in *RuncPsRequest, opts ...grpc.CallOption) (*RuncPsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuncPsResponse)
	err := c.cc.Invoke(ctx, RuncService_Ps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runcServiceClient) Checkpoint(ctx context.Context, in *RuncCheckpointRequest, opts ...grpc.CallOption) (*RuncCheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuncCheckpointResponse)
	err := c.cc.Invoke(ctx, RuncService_Checkpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runcServiceClient) Restore(ctx context.Context, in *RuncRestoreRequest, opts ...grpc.CallOption) (*RuncRestoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuncRestoreResponse)
	err := c.cc.Invoke(ctx, RuncService_Restore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runcServiceClient) Update(ctx context.Context, in *RuncUpdateRequest, opts ...grpc.CallOption) (*RuncUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuncUpdateResponse)
	err := c.cc.Invoke(ctx, RuncService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runcServiceClient) NewTempConsoleSocket(ctx context.Context, in *RuncNewTempConsoleSocketRequest, opts ...grpc.CallOption) (*RuncNewTempConsoleSocketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuncNewTempConsoleSocketResponse)
	err := c.cc.Invoke(ctx, RuncService_NewTempConsoleSocket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runcServiceClient) ReadPidFile(ctx context.Context, in *RuncReadPidFileRequest, opts ...grpc.CallOption) (*RuncReadPidFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuncReadPidFileResponse)
	err := c.cc.Invoke(ctx, RuncService_ReadPidFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuncServiceServer is the server API for RuncService service.
// All implementations should embed UnimplementedRuncServiceServer
// for forward compatibility.
type RuncServiceServer interface {
	// Ping checks if the service is alive
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// Create creates a new container
	Create(context.Context, *RuncCreateRequest) (*RuncCreateResponse, error)
	// Start will start an already created container
	Start(context.Context, *RuncStartRequest) (*RuncStartResponse, error)
	// Exec executes an additional process inside the container
	Exec(context.Context, *RuncExecRequest) (*RuncExecResponse, error)
	// Delete deletes the container
	Delete(context.Context, *RuncDeleteRequest) (*RuncDeleteResponse, error)
	// Kill sends the specified signal to the container
	Kill(context.Context, *RuncKillRequest) (*RuncKillResponse, error)
	// Pause the container with the provided id
	Pause(context.Context, *RuncPauseRequest) (*RuncPauseResponse, error)
	// Resume the container with the provided id
	Resume(context.Context, *RuncResumeRequest) (*RuncResumeResponse, error)
	// Ps lists all the processes inside the container returning their pids
	Ps(context.Context, *RuncPsRequest) (*RuncPsResponse, error)
	// Checkpoint checkpoints the container
	Checkpoint(context.Context, *RuncCheckpointRequest) (*RuncCheckpointResponse, error)
	// Restore restores the container from a checkpoint
	Restore(context.Context, *RuncRestoreRequest) (*RuncRestoreResponse, error)
	// Update updates the container resources
	Update(context.Context, *RuncUpdateRequest) (*RuncUpdateResponse, error)
	NewTempConsoleSocket(context.Context, *RuncNewTempConsoleSocketRequest) (*RuncNewTempConsoleSocketResponse, error)
	ReadPidFile(context.Context, *RuncReadPidFileRequest) (*RuncReadPidFileResponse, error)
}

// UnimplementedRuncServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuncServiceServer struct{}

func (UnimplementedRuncServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedRuncServiceServer) Create(context.Context, *RuncCreateRequest) (*RuncCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedRuncServiceServer) Start(context.Context, *RuncStartRequest) (*RuncStartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedRuncServiceServer) Exec(context.Context, *RuncExecRequest) (*RuncExecResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedRuncServiceServer) Delete(context.Context, *RuncDeleteRequest) (*RuncDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedRuncServiceServer) Kill(context.Context, *RuncKillRequest) (*RuncKillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Kill not implemented")
}
func (UnimplementedRuncServiceServer) Pause(context.Context, *RuncPauseRequest) (*RuncPauseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pause not implemented")
}
func (UnimplementedRuncServiceServer) Resume(context.Context, *RuncResumeRequest) (*RuncResumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Resume not implemented")
}
func (UnimplementedRuncServiceServer) Ps(context.Context, *RuncPsRequest) (*RuncPsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ps not implemented")
}
func (UnimplementedRuncServiceServer) Checkpoint(context.Context, *RuncCheckpointRequest) (*RuncCheckpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Checkpoint not implemented")
}
func (UnimplementedRuncServiceServer) Restore(context.Context, *RuncRestoreRequest) (*RuncRestoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedRuncServiceServer) Update(context.Context, *RuncUpdateRequest) (*RuncUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedRuncServiceServer) NewTempConsoleSocket(context.Context, *RuncNewTempConsoleSocketRequest) (*RuncNewTempConsoleSocketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewTempConsoleSocket not implemented")
}
func (UnimplementedRuncServiceServer) ReadPidFile(context.Context, *RuncReadPidFileRequest) (*RuncReadPidFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadPidFile not implemented")
}
func (UnimplementedRuncServiceServer) testEmbeddedByValue() {}

// UnsafeRuncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuncServiceServer will
// result in compilation errors.
type UnsafeRuncServiceServer interface {
	mustEmbedUnimplementedRuncServiceServer()
}

func RegisterRuncServiceServer(s grpc.ServiceRegistrar, srv RuncServiceServer) {
	// If the following call pancis, it indicates UnimplementedRuncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RuncService_ServiceDesc, srv)
}

func _RuncService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuncServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuncService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuncServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuncService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuncCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuncServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuncService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuncServiceServer).Create(ctx, req.(*RuncCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuncService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuncStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuncServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuncService_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuncServiceServer).Start(ctx, req.(*RuncStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuncService_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuncExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuncServiceServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuncService_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuncServiceServer).Exec(ctx, req.(*RuncExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuncService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuncDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuncServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuncService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuncServiceServer).Delete(ctx, req.(*RuncDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuncService_Kill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuncKillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuncServiceServer).Kill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuncService_Kill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuncServiceServer).Kill(ctx, req.(*RuncKillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuncService_Pause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuncPauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuncServiceServer).Pause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuncService_Pause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuncServiceServer).Pause(ctx, req.(*RuncPauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuncService_Resume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuncResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuncServiceServer).Resume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuncService_Resume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuncServiceServer).Resume(ctx, req.(*RuncResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuncService_Ps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuncPsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuncServiceServer).Ps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuncService_Ps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuncServiceServer).Ps(ctx, req.(*RuncPsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuncService_Checkpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuncCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuncServiceServer).Checkpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuncService_Checkpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuncServiceServer).Checkpoint(ctx, req.(*RuncCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuncService_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuncRestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuncServiceServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuncService_Restore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuncServiceServer).Restore(ctx, req.(*RuncRestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuncService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuncUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuncServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuncService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuncServiceServer).Update(ctx, req.(*RuncUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuncService_NewTempConsoleSocket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuncNewTempConsoleSocketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuncServiceServer).NewTempConsoleSocket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuncService_NewTempConsoleSocket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuncServiceServer).NewTempConsoleSocket(ctx, req.(*RuncNewTempConsoleSocketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuncService_ReadPidFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuncReadPidFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuncServiceServer).ReadPidFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuncService_ReadPidFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuncServiceServer).ReadPidFile(ctx, req.(*RuncReadPidFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RuncService_ServiceDesc is the grpc.ServiceDesc for RuncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runv.v1.RuncService",
	HandlerType: (*RuncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _RuncService_Ping_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _RuncService_Create_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _RuncService_Start_Handler,
		},
		{
			MethodName: "Exec",
			Handler:    _RuncService_Exec_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _RuncService_Delete_Handler,
		},
		{
			MethodName: "Kill",
			Handler:    _RuncService_Kill_Handler,
		},
		{
			MethodName: "Pause",
			Handler:    _RuncService_Pause_Handler,
		},
		{
			MethodName: "Resume",
			Handler:    _RuncService_Resume_Handler,
		},
		{
			MethodName: "Ps",
			Handler:    _RuncService_Ps_Handler,
		},
		{
			MethodName: "Checkpoint",
			Handler:    _RuncService_Checkpoint_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _RuncService_Restore_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _RuncService_Update_Handler,
		},
		{
			MethodName: "NewTempConsoleSocket",
			Handler:    _RuncService_NewTempConsoleSocket_Handler,
		},
		{
			MethodName: "ReadPidFile",
			Handler:    _RuncService_ReadPidFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/runc.proto",
}

const (
	RuncExtrasService_State_FullMethodName   = "/runv.v1.RuncExtrasService/State"
	RuncExtrasService_Run_FullMethodName     = "/runv.v1.RuncExtrasService/Run"
	RuncExtrasService_Stats_FullMethodName   = "/runv.v1.RuncExtrasService/Stats"
	RuncExtrasService_Events_FullMethodName  = "/runv.v1.RuncExtrasService/Events"
	RuncExtrasService_List_FullMethodName    = "/runv.v1.RuncExtrasService/List"
	RuncExtrasService_Version_FullMethodName = "/runv.v1.RuncExtrasService/Version"
	RuncExtrasService_Top_FullMethodName     = "/runv.v1.RuncExtrasService/Top"
)

// RuncExtrasServiceClient is the client API for RuncExtrasService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RuncExtrasServiceClient interface {
	State(ctx context.Context, in *RuncStateRequest, opts ...grpc.CallOption) (*RuncStateResponse, error)
	Run(ctx context.Context, in *RuncRunRequest, opts ...grpc.CallOption) (*RuncRunResponse, error)
	Stats(ctx context.Context, in *RuncStatsRequest, opts ...grpc.CallOption) (*RuncStatsResponse, error)
	Events(ctx context.Context, in *RuncEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RuncEvent], error)
	List(ctx context.Context, in *RuncListRequest, opts ...grpc.CallOption) (*RuncListResponse, error)
	Version(ctx context.Context, in *RuncVersionRequest, opts ...grpc.CallOption) (*RuncVersionResponse, error)
	Top(ctx context.Context, in *RuncTopRequest, opts ...grpc.CallOption) (*RuncTopResponse, error)
}

type runcExtrasServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRuncExtrasServiceClient(cc grpc.ClientConnInterface) RuncExtrasServiceClient {
	return &runcExtrasServiceClient{cc}
}

func (c *runcExtrasServiceClient) State(ctx context.Context, in *RuncStateRequest, opts ...grpc.CallOption) (*RuncStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuncStateResponse)
	err := c.cc.Invoke(ctx, RuncExtrasService_State_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runcExtrasServiceClient) Run(ctx context.Context, in *RuncRunRequest, opts ...grpc.CallOption) (*RuncRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuncRunResponse)
	err := c.cc.Invoke(ctx, RuncExtrasService_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runcExtrasServiceClient) Stats(ctx context.Context, in *RuncStatsRequest, opts ...grpc.CallOption) (*RuncStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuncStatsResponse)
	err := c.cc.Invoke(ctx, RuncExtrasService_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runcExtrasServiceClient) Events(ctx context.Context, in *RuncEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RuncEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RuncExtrasService_ServiceDesc.Streams[0], RuncExtrasService_Events_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RuncEventsRequest, RuncEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuncExtrasService_EventsClient = grpc.ServerStreamingClient[RuncEvent]

func (c *runcExtrasServiceClient) List(ctx context.Context, in *RuncListRequest, opts ...grpc.CallOption) (*RuncListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuncListResponse)
	err := c.cc.Invoke(ctx, RuncExtrasService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runcExtrasServiceClient) Version(ctx context.Context, in *RuncVersionRequest, opts ...grpc.CallOption) (*RuncVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuncVersionResponse)
	err := c.cc.Invoke(ctx, RuncExtrasService_Version_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runcExtrasServiceClient) Top(ctx context.Context, in *RuncTopRequest, opts ...grpc.CallOption) (*RuncTopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuncTopResponse)
	err := c.cc.Invoke(ctx, RuncExtrasService_Top_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuncExtrasServiceServer is the server API for RuncExtrasService service.
// All implementations should embed UnimplementedRuncExtrasServiceServer
// for forward compatibility.
type RuncExtrasServiceServer interface {
	State(context.Context, *RuncStateRequest) (*RuncStateResponse, error)
	Run(context.Context, *RuncRunRequest) (*RuncRunResponse, error)
	Stats(context.Context, *RuncStatsRequest) (*RuncStatsResponse, error)
	Events(*RuncEventsRequest, grpc.ServerStreamingServer[RuncEvent]) error
	List(context.Context, *RuncListRequest) (*RuncListResponse, error)
	Version(context.Context, *RuncVersionRequest) (*RuncVersionResponse, error)
	Top(context.Context, *RuncTopRequest) (*RuncTopResponse, error)
}

// UnimplementedRuncExtrasServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuncExtrasServiceServer struct{}

func (UnimplementedRuncExtrasServiceServer) State(context.Context, *RuncStateRequest) (*RuncStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method State not implemented")
}
func (UnimplementedRuncExtrasServiceServer) Run(context.Context, *RuncRunRequest) (*RuncRunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedRuncExtrasServiceServer) Stats(context.Context, *RuncStatsRequest) (*RuncStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedRuncExtrasServiceServer) Events(*RuncEventsRequest, grpc.ServerStreamingServer[RuncEvent]) error {
	return status.Errorf(codes.Unimplemented, "method Events not implemented")
}
func (UnimplementedRuncExtrasServiceServer) List(context.Context, *RuncListRequest) (*RuncListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedRuncExtrasServiceServer) Version(context.Context, *RuncVersionRequest) (*RuncVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedRuncExtrasServiceServer) Top(context.Context, *RuncTopRequest) (*RuncTopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Top not implemented")
}
func (UnimplementedRuncExtrasServiceServer) testEmbeddedByValue() {}

// UnsafeRuncExtrasServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuncExtrasServiceServer will
// result in compilation errors.
type UnsafeRuncExtrasServiceServer interface {
	mustEmbedUnimplementedRuncExtrasServiceServer()
}

func RegisterRuncExtrasServiceServer(s grpc.ServiceRegistrar, srv RuncExtrasServiceServer) {
	// If the following call pancis, it indicates UnimplementedRuncExtrasServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RuncExtrasService_ServiceDesc, srv)
}

func _RuncExtrasService_State_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuncStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuncExtrasServiceServer).State(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuncExtrasService_State_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuncExtrasServiceServer).State(ctx, req.(*RuncStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuncExtrasService_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuncRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuncExtrasServiceServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuncExtrasService_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuncExtrasServiceServer).Run(ctx, req.(*RuncRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuncExtrasService_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuncStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuncExtrasServiceServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuncExtrasService_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuncExtrasServiceServer).Stats(ctx, req.(*RuncStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuncExtrasService_Events_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RuncEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RuncExtrasServiceServer).Events(m, &grpc.GenericServerStream[RuncEventsRequest, RuncEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuncExtrasService_EventsServer = grpc.ServerStreamingServer[RuncEvent]

func _RuncExtrasService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuncListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuncExtrasServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuncExtrasService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuncExtrasServiceServer).List(ctx, req.(*RuncListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuncExtrasService_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuncVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuncExtrasServiceServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuncExtrasService_Version_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuncExtrasServiceServer).Version(ctx, req.(*RuncVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuncExtrasService_Top_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuncTopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuncExtrasServiceServer).Top(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuncExtrasService_Top_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuncExtrasServiceServer).Top(ctx, req.(*RuncTopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RuncExtrasService_ServiceDesc is the grpc.ServiceDesc for RuncExtrasService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuncExtrasService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runv.v1.RuncExtrasService",
	HandlerType: (*RuncExtrasServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "State",
			Handler:    _RuncExtrasService_State_Handler,
		},
		{
			MethodName: "Run",
			Handler:    _RuncExtrasService_Run_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _RuncExtrasService_Stats_Handler,
		},
		{
			MethodName: "List",
			Handler:    _RuncExtrasService_List_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _RuncExtrasService_Version_Handler,
		},
		{
			MethodName: "Top",
			Handler:    _RuncExtrasService_Top_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Events",
			Handler:       _RuncExtrasService_Events_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "v1/runc.proto",
}
