// Code generated by protoc-gen-go-opaque-helpers. DO NOT EDIT.
// source: v1/shim.proto

package runmv1

import (
	protovalidate "buf.build/go/protovalidate"
)

// NewShimKillRequest creates a new ShimKillRequest using the builder
func NewShimKillRequest(b *ShimKillRequest_builder) *ShimKillRequest {
	return b.Build()
}

// NewShimKillRequestE creates a new ShimKillRequest using the builder with validation
func NewShimKillRequestE(b *ShimKillRequest_builder) (*ShimKillRequest, error) {
	m := b.Build()
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NewShimKillResponse creates a new ShimKillResponse using the builder
func NewShimKillResponse(b *ShimKillResponse_builder) *ShimKillResponse {
	return b.Build()
}

// NewShimKillResponseE creates a new ShimKillResponse using the builder with validation
func NewShimKillResponseE(b *ShimKillResponse_builder) (*ShimKillResponse, error) {
	m := b.Build()
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NewShimFeaturesRequest creates a new ShimFeaturesRequest using the builder
func NewShimFeaturesRequest(b *ShimFeaturesRequest_builder) *ShimFeaturesRequest {
	return b.Build()
}

// NewShimFeaturesRequestE creates a new ShimFeaturesRequest using the builder with validation
func NewShimFeaturesRequestE(b *ShimFeaturesRequest_builder) (*ShimFeaturesRequest, error) {
	m := b.Build()
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NewShimFeaturesResponse creates a new ShimFeaturesResponse using the builder
func NewShimFeaturesResponse(b *ShimFeaturesResponse_builder) *ShimFeaturesResponse {
	return b.Build()
}

// NewShimFeaturesResponseE creates a new ShimFeaturesResponse using the builder with validation
func NewShimFeaturesResponseE(b *ShimFeaturesResponse_builder) (*ShimFeaturesResponse, error) {
	m := b.Build()
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}
